import { Badge } from "@/components/ui/badge";
import { type TryOnResult } from "@/types/tryon";

const FIT_COLORS: Record<string, string> = {
  tight: "bg-red-500/10 text-red-600 border-red-200",
  standard: "bg-green-500/10 text-green-600 border-green-200",
  loose: "bg-blue-500/10 text-blue-600 border-blue-200",
  short: "bg-yellow-500/10 text-yellow-600 border-yellow-200",
  long: "bg-purple-500/10 text-purple-600 border-purple-200",
};

interface ResultStepProps {
  result: TryOnResult | null;
  isLoading: boolean;
}

export default function ResultStep({ result, isLoading }: ResultStepProps) {
  if (isLoading) {
    return (
      <div className="flex flex-col items-center gap-4 py-12">
        <div className="size-12 rounded-full border-4 border-primary border-t-transparent animate-spin" />
        <div className="text-center">
          <p className="font-medium">Generating your try-on…</p>
          <p className="text-sm text-muted-foreground mt-1">
            This can take 30–60 seconds with the free AI provider.
          </p>
        </div>
        {/* Fake progress bar for perceived performance */}
        <div className="w-full max-w-xs h-1.5 rounded-full bg-muted overflow-hidden">
          <div className="h-full bg-primary rounded-full animate-[progress_45s_ease-in-out_forwards] w-0" />
        </div>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="text-center py-12 text-muted-foreground">
        Complete the previous steps and click <strong>Generate</strong>.
      </div>
    );
  }

  const { fit_prediction } = result;

  return (
    <div className="space-y-6">
      {/* Generated image */}
      <div className="flex justify-center">
        <img
          src={`data:${result.mime_type};base64,${result.image_base64}`}
          alt="AI-generated try-on result"
          className="max-h-96 rounded-xl border border-border object-contain shadow-sm"
        />
      </div>

      {/* Fit prediction */}
      <div className="rounded-xl border border-border p-4 space-y-3">
        <h3 className="text-sm font-semibold">Fit Prediction</h3>
        <div className="flex flex-wrap gap-2">
          <Badge className={FIT_COLORS[fit_prediction.chest_fit]}>
            Chest: {fit_prediction.chest_fit}
          </Badge>
          <Badge className={FIT_COLORS[fit_prediction.length]}>
            Length: {fit_prediction.length}
          </Badge>
          <Badge className={FIT_COLORS[fit_prediction.sleeve]}>
            Sleeve: {fit_prediction.sleeve}
          </Badge>
        </div>
        <p className="text-sm text-muted-foreground">
          {fit_prediction.summary}
        </p>
      </div>

      <p className="text-xs text-muted-foreground text-center">
        Generated by <span className="font-medium">{result.provider}</span>{" "}
        provider · Results are AI-generated approximations
      </p>
    </div>
  );
}
